### ISSUE TITLE
Home > Notícias > PHP

### ISSUE THREAD

**Issue by diegorojas** [brainwp/polis-theme#13]
Desenvolver query que misture os CPTs Noticias e Ações.

Criar um tamanho de Thumbnail para Noticias em Destaque que seja o mesmo usado no topo da single de cada post.

Com a informação de qual categoria pertence, imagem destacada, titúlo, excerpt e leia mais.

![home-slider-noticias](https://cloud.githubusercontent.com/assets/3632627/2977523/61788ce0-dbac-11e3-9256-bb2e94be30ac.jpg)

**Comment by matheusgimenez** [comment]
Feito
