### ISSUE TITLE
[Animação Home] Imagens estão desalinhadas

### ISSUE THREAD

**Issue by LuwkasLima** [brainwp/polis-theme#47]
Quando interagimos com a "mandala", aparentemente ela se move, ou seja, as imagens que compõem a animação não estão centralizadas. 

Me parece que uma das imagens está saindo menos que as outras:

![image](https://cloud.githubusercontent.com/assets/5949986/11825066/a4a6821a-a342-11e5-928d-8e161fe5e690.png)

![image](https://cloud.githubusercontent.com/assets/5949986/11825081/b2ed8bc0-a342-11e5-92ca-6c01181634cc.png)

**Comment by matheusgimenez** [comment]
Veja se resolveu
